apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sample-horizontalpodautoscaler
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-deployment
  targetCPUUtilizationPercentage: 50
